### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by cyosp**
Hi Thibaub,

I've classified current Docker container and created a new one from Debian/Stretch.

Best regards,
CYOSP

### CODE REVIEW

**Comment by kevynb** [comment]
Hello, I just tested it and It works like a charm. However maybe we could also add a variable to mount the Photo directory as a shared directory? So that they can be persisted between container restarts.
I'm asking this here instead of creating an issue because the PR has not been merged yet.

**Comment by cyosp** [comment]
Hi @kevynb,

Thank you to have tested this feature and for your feedback !
Docker allows to map a directory from host inside a container using option: `-v <host directory>:<container directory>`.
I study your request and let you know.

Best regards,
CYOSP

**Comment by cyosp** [comment]
Hi @kevynb,

I've implemented the feature.
You will find in README.md details about how to use it.
Can you please try it and let me know ?

Best regards,
CYOSP

**Comment by thibaud-rohmer** [comment]
@kevynb, I'll have a look on your "review" on this and try to merge this
feature when it's ready. Thanks for the hard work, @cyosp !

**Comment by cyosp** [comment]
@thibaud-rohmer thank you !
Waiting now @kevynb feedback.

**Comment by kevynb** [comment]
I wonder if the explanation you added about the user group `www-data` will be valid in every case because of Docker way of mapping uids, were it would not match with the real host www-data user id but it might be an edge case. People will surely create an issue if that happens.

Although I'm not sure we need to share the generated folder, this could remove the need to chown the `generated` folder. Doing like `-v ${PHOTOSHOW_HOST_DIRECTORY}:/opt/PhotoShow/Photos`

What do you guys think?

Otherwise it looks good to me!
Thanks a lot @cyosp for the update on your MR!

**Comment by cyosp** [comment]
You are right about `www-data` and I check to solve that.

About `generated`, it's important to keep it also outside container because it contains all configuration which could have been defined using admin account : folders public/private, users/groups...

**Comment by cyosp** [comment]
Hi @kevynb, are you ok with modification in order to @thibaud-rohmer perform the merge request ?

**Comment by thibaud-rohmer** [comment]
(I'm lurking in the shadows... waiting... :D )

**Comment by kevynb** [comment]
Come out of the shadows then! I'm ok too :)

**Pull request merged**
