### PR TITLE
Selectable album thumbnail

### PR DESCRIPTION
**Pull request by alesc**
- select cover from image in album
- define default cover filename in settings (default is ".cover.jpg")

### CODE REVIEW

**Comment by gboudreau** [comment]
@alesc Why did you close your own PR? Is there a problem with it, or ..?

**Comment by alesc** [comment]
I forgot to variabilize some elements in Judge.php, I've closed this PR to make necessary changes and I will submit it again. 
It is the first time I'm really using github, I don't know if I can let a PR open and make changes ...

**Comment by thibaud-rohmer** [comment]
Very good practice, thanks that !

You can leave the PR open (and every new commit you add to your branch is
directly added in the PR). But it would mean that I (the reviewer) might
accept and merge it before you've made the edits. So I prefer if you do it
like that :)

**Comment by alesc** [comment]
Due to force-push I did, githut won't reopen this PR. 
So I will make a new one. 
Sorry for spam.

**Pull request closed without merging**
